/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AuthRequest,
  AuthResponse,
  GoogleAuthRequest
} from '.././schemas';




  export const register = <TData = AxiosResponse<AuthResponse>>(
    authRequest: AuthRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/register`,
      authRequest,options
    );
  }
export const login = <TData = AxiosResponse<AuthResponse>>(
    authRequest: AuthRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/login`,
      authRequest,options
    );
  }
export const loginWithGoogle = <TData = AxiosResponse<AuthResponse>>(
    googleAuthRequest: GoogleAuthRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/google`,
      googleAuthRequest,options
    );
  }
export const testDb = <TData = AxiosResponse<string>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/auth/test-db`,options
    );
  }
export type RegisterResult = AxiosResponse<AuthResponse>
export type LoginResult = AxiosResponse<AuthResponse>
export type LoginWithGoogleResult = AxiosResponse<AuthResponse>
export type TestDbResult = AxiosResponse<string>
