/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AuthResponseRole = typeof AuthResponseRole[keyof typeof AuthResponseRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthResponseRole = {
  USER: 'USER',
  BUSINESS: 'BUSINESS',
  ADMIN: 'ADMIN',
} as const;
