/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AuthResponseRole } from './authResponseRole';

export interface AuthResponse {
  token?: string;
  role?: AuthResponseRole;
}
