/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Google OAuth2 login redirect information
 */
export interface GoogleLoginResponse {
  /** URL to redirect the user for Google authentication */
  authUrl?: string;
  /** Information message about the redirect */
  message?: string;
}
