/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type HackathonRequestType = typeof HackathonRequestType[keyof typeof HackathonRequestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HackathonRequestType = {
  WRITING: 'WRITING',
  AUDIO: 'AUDIO',
  ART: 'ART',
  BUSINESS: 'BUSINESS',
} as const;
