/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { HackathonRequestType } from './hackathonRequestType';

export interface HackathonRequest {
  name?: string;
  description?: string;
  type?: HackathonRequestType;
}
