/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface LinkUpdateRequest {
  /** @minLength 1 */
  platformName: string;
  /** @minLength 1 */
  url: string;
}
