/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface LinkResponse {
  id?: number;
  platformName?: string;
  url?: string;
}
