/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TeamCreateRequest {
  /** @minLength 1 */
  name: string;
  hackathonId: number;
  userId: number;
}
